---
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ChatwootInstanceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
  ChatwootInstanceRolePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: ChatwootInstancePolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: '*'
            Resource: '*'
      Roles:
        - Ref: ChatwootInstanceRole
  ChatwootInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref ChatwootInstanceRole